### ISSUE TITLE
NFS bugs ?

### ISSUE THREAD

**Issue by HeartBtz** [LetrixZ/faccina#28]
Hi, still looking for bugs... 

- I've just switched back to NFS, on a new server, and once again, I find myself indexing only part of my files, whereas when I put them on a local disk, everything seems to work when indexing.
`root@VM120-X:/opt/doujin.eeeeeeeee.eu/faccina 21:11:13 ✔ ➤ ll ../archives/anchira.to_1-1000/ | wc -l`
`199`
`root@VM120-X:/opt/doujin.eeeeeeeeeee.eu/faccina 21:12:10 ✔ ➤ bun cli index --reindex`
`Found 106 files to index`

-I've just reinstalled everything on a new, clean Debian server (basic virtual machine, nothing special, clean bun installation, according to your procedure, then addition of an NFS directory, in which I store the archives).
I correctly did the `bun install`, then the bun run build, everything starts correctly, but when I create an account, I can't connect to it afterwards: 
```bash
root@VM120-X:/opt/xxx/faccina 21:12:22 ✔ ➤ bun start
$ bun ./serve.ts
[PID: 3435] Listening on 0.0.0.0:3000
```
```yaml
[2024-11-16T20:12:36.902Z] {
  action: "search_main",
  payload: {
    data: {
      query: "",
      page: 1,
      limit: 24,
    },
    userId: undefined,
  },
}
[2024-11-16T20:12:48.566Z] {
  action: "user_login",
  payload: {
    userId: "ai2tjavv5evb5o7v",
  },
}
[2024-11-16T20:12:48.589Z] {
  action: "search_main",
  payload: {
    data: {
      query: "",
      page: 1,
      limit: 24,
    },
    userId: undefined,
  },
}
```
nothing to do, I no longer have the connection options... Are there any other prerequisites? 

When I do the bun install : 
```
bun install v1.1.34 (5e5e7c60)

Checked 863 installs across 981 packages (no changes) [206.00ms]
```

Encore merci et désolé si c'est encore une gaffe :D

**Comment by LetrixZ** [comment]
I'll see if I can replicate your environment.

For the login part, what browser are you using and do you have Javascript disabled?

**Comment by HeartBtz** [comment]
add me on discord (heartbtz) if u want an access on mine for testing. 

Opera, but also tested on firefox. 
Javascript is enabled everywhere :D

**Comment by LetrixZ** [comment]
I found the login issue. You need to either be on localhost or in a HTTPS environment for the session cookie to be set.

I now added the option to specify if the session cookie should be secure (require HTTPS) or not.

```toml
[site]
secure_session_cookie = true # default
```
