### ISSUE TITLE
Tag exclusion has no effect on reading history page

### ISSUE THREAD

**Issue by WiseMan6** [LetrixZ/faccina#30]
config.toml
```toml
...
[[site.gallery_listing.tag_exclude]]
name = ['original', 'original work']
ignore_case = true
...
```

As expected, home, favorites, and collections don't have "Original Work" label on its entries, however:
![Arc_arVkjH994E](https://github.com/user-attachments/assets/70d27375-727f-473f-ae94-1f94ae2ff7da)
